[build]
  command = "ng build --prod"
  publish = "dist/your-project-name"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "https://your-api-domain.com/:splat"
  status = 200
